apiVersion: v1
kind: ConfigMap
metadata:
  name: n8n-cm
data:
  GENERIC_TIMEZONE: "Europe/Copenhagen"
  TZ: "Europe/Copenhagen"
  N8N_PORT: "3000"
  N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS: "true"
  N8N_RUNNERS_ENABLED: "true"
  N8N_SECURE_COOKIE: "false"
  DB_TYPE: "postgresdb"
  # All the values below are sensitive and they are hardcoded only for this phase. Other phase will store them safe
  DB_POSTGRESDB_DATABASE: "customerdb"
  DB_POSTGRESDB_HOST: "psql-rds.clyuc4e6ci6m.eu-west-1.rds.amazonaws.com" # Replace it with your endpoint
  DB_POSTGRESDB_PASSWORD: "n8n-password"
  DB_POSTGRESDB_PORT: "5432"
  DB_POSTGRESDB_USER: "psqladmin"
